services:
  mongodb:
    image: mongo:7.0
    container_name: chronicle-mongodb

    volumes:
      - mongodb_data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: ghcr.io/mrtuxcoder/chronicle-backend:latest

    environment:
      MONGODB_URI: mongodb://mongodb:27017/chronicle

    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: ghcr.io/mrtuxcoder/chronicle-frontend:latest

    ports:
      - "80:80"

    depends_on:
      - backend

volumes:
  mongodb_data: