name: CI Workflow
on:
  push:
    branches:
      - main
  
env:
  MONGO_URI: mongodb://localhost:27017/chronicle_test
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PORT: ${{ secrets.PORT }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: copy repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
                 frontend/package-lock.json
                 backend/package-lock.json

      - name: install dependencies client
        run: npm ci
        working-directory: frontend
      - name: install dependencies server
        run: npm ci
        working-directory: backend
      - name: run lint client
        run: npm run lint
        working-directory: frontend
      - name: run lint server
        run: npm run lint
        working-directory: backend

  test:
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: copy repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
                 frontend/package-lock.json
                 backend/package-lock.json

      - name: install dependencies server
        run: npm ci
        working-directory: backend
      - name: run tests server
        run: npm test
        working-directory: backend
      
    
