name: CI Workflow
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: copy repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: install dependencies client
        run: npm install
        working-directory: frontend
      - name: install dependencies server
        run: npm install
        working-directory: backend
      - name: run lint client
        run: npm run lint
        working-directory: frontend
      - name: run lint server
        run: npm run lint
        working-directory: backend
      
